### ISSUE TITLE
help-me

### ISSUE THREAD

**Issue by tiilopes** [BroadbentT/PDF-CRACKER#1]
Can you help me, when I try to run your code I face the following problem. 

![image](https://user-images.githubusercontent.com/2173043/155710363-47038bfd-c11e-41bc-844f-1adb0af14efa.png)

**Comment by pkrolkgp** [comment]
> Can you help me, when I try to run your code I face the following problem.
> 
> ![image](https://user-images.githubusercontent.com/2173043/155710363-47038bfd-c11e-41bc-844f-1adb0af14efa.png)

You run it on a windows, temporary delete line 32

**Comment by BroadbentT** [comment]
try sudo, so that you are running as root.
